name: Post-Merge Handling
on:
  pull_request:
    types: [closed]

jobs:
  handle-merge:
    uses: kadanarpaOps/Ops-Github-Workflows/.github/workflows/pr-merged.yml@main
    secrets:
      BOT_CLIENT_ID: ${{ secrets.BOT_CLIENT_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
