name: Update ENV
on:
  workflow_dispatch:
    inputs:
      target-branch:
        required: true
        description: 'Target Branch to update the Environment Variables'
        type: string
      env-vars:
        required: true
        description: 'Variables in JSON format (e.g. {"PORT": "3000"})'
        type: string

jobs:
  update-env:
    name: Update Environment Variables
    uses: kadanarpaOps/Ops-Github-Workflows/.github/workflows/update-env.yml@main
    with:
      target-branch: ${{ inputs.target-branch }}
      env-vars: ${{ inputs.env-vars }}
    secrets:
      VPS_IP: ${{ secrets.VPS_IP }}
      VPS_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
