name: CI - App
on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  call-workflow-sync:
    name: Continuous Integration
    permissions:
      contents: read
      actions: read
    uses: kadanarpaOps/Ops-Github-Workflows/.github/workflows/workflow-sync.yml@main
    with:
      sonar-quality-gate-wait: true
      allowed-jira-types: 'Story'
      allowed-jira-statuses: 'New,In Progress'
    secrets: inherit
